# Generated by Django 2.2.7 on 2019-11-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('key', models.IntegerField(primary_key=True, serialize=False)),
                ('menus', models.CharField(max_length=500)),
                ('prices', models.CharField(max_length=500)),
                ('counts', models.CharField(max_length=500)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='image_url',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
