# Generated by Django 2.2.7 on 2019-11-08 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191108_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='done',
        ),
    ]
